### ISSUE TITLE
ImportError: No module named 'ib'

### ISSUE THREAD

**Issue by SageKing** [mementum/backtrader#100]
I'm getting an import error when trying to run the Quickstart tutorial code here....

```
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import backtrader as bt

if __name__ == '__main__':
    cerebro = bt.Cerebro()

    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

    cerebro.run()

    print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
```

The error:

```
Traceback (most recent call last):
  File "/Users/user/Documents/backtester_testing_2/backtester_test.py", line 4, in <module>
    import backtrader as bt
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/backtrader/__init__.py", line 54, in <module>
    from . import feeds
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/backtrader/feeds/__init__.py", line 32, in <module>
    from .ibdata import *
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/backtrader/feeds/ibdata.py", line 30, in <module>
    from backtrader.stores import ibstore
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/backtrader/stores/__init__.py", line 27, in <module>
    from .ibstore import IBStore
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/backtrader/stores/ibstore.py", line 33, in <module>
    from ib.ext.Contract import Contract
ImportError: No module named 'ib'

```

I'm running a virtual environment in Pycharm Python 3.

**Comment by mementum** [comment]
This was a packaging error in Release 1.3.2.92 and corrected in 1.3.3.93 with ticket #99

Release 1.3.3.93: https://github.com/mementum/backtrader/releases/tag/1.3.3.92
At PyPI: https://pypi.python.org/pypi/backtrader/1.3.3.92
