### ISSUE TITLE
issues when running talibtest.py on mac

### ISSUE THREAD

**Issue by shlwang** [mementum/backtrader#140]
```
Traceback (most recent call last):
  File "talibtest.py", line 192, in <module>
    runstrat()
  File "talibtest.py", line 136, in runstrat
    cerebro.run(runcone=not args.use_next, stdstats=False)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/backtrader/cerebro.py", line 680, in run
    runstrat = self.runstrategies(iterstrat)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/backtrader/cerebro.py", line 725, in runstrategies
    strat = stratcls(self, *sargs, **skwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/backtrader/metabase.py", line 87, in __call__
    _obj, args, kwargs = cls.doinit(_obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/backtrader/metabase.py", line 77, in doinit
    _obj.__init__(*args, **kwargs)
  File "talibtest.py", line 39, in __init__
    bt.talib.CDLDOJI(self.data.open, self.data.high,
AttributeError: module 'backtrader.talib' has no attribute 'CDLDOJI'
```

Any help would be appreciated.

**Comment by mementum** [comment]
It seems you haven't installed the required dependencies.

> Requirements
>   - Python wrapper for TA-Lib
>   - Any dependencies needed by it (for example numpy)

http://backtrader.readthedocs.io/en/latest/talib/talib.html

**Comment by shlwang** [comment]
Thanks a lot. @mementum
