### ISSUE TITLE
plotting issue: AttributeError: 'OptReturn' object has no attribute 'datas'

### ISSUE THREAD

**Issue by diseq** [mementum/backtrader#141]
running quickstart10.py

Version:
```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__version__
'1.5.2'
```
Log:
```
2000-12-22, BUY EXECUTED, Price: 28.65, Cost: 286.50, Comm 0.00
2000-12-22, Close, 30.06
2000-12-26, Close, 29.17
2000-12-27, Close, 28.94
2000-12-28, Close, 29.29
2000-12-29, Close, 27.41
2000-12-29, SELL CREATE, 27.41
Final Portfolio Value: 981.00
Traceback (most recent call last):
  File "quickstart10.py", line 175, in <module>
    cerebro.plot()
  File "C:\tools\lang\python3-amd64\lib\site-packages\backtrader\cerebro.py", line 607, in plot
    plotter.plot(strat, numfigs=numfigs)
  File "C:\tools\lang\python3-amd64\lib\site-packages\backtrader\plot\plot.py", line 112, in plot
    if not strategy.datas:
AttributeError: 'OptReturn' object has no attribute 'datas'
```

**Comment by diseq** [comment]
Thanks a lot for the fix! your work with the framework is great.
I hope to contribute anytime soon.
