### ISSUE TITLE
OandaStore 

### ISSUE THREAD

**Issue by pythonbacktrader** [mementum/backtrader#152]
Hi mementum,

I'm very grateful to have found your backtrader libary, it is very well-written and it has huge potential.  However I face two errors whenever I try to use Oanda: 

```
Exception in thread Thread-6:
Traceback (most recent call last):
File "C:\Users\Gustav\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
  self.run()
File "C:\Users\Gustav\Anaconda2\lib\threading.py", line 754, in run
  self.__target(*self.__args, **self.__kwargs)
File "C:\Users\Gustav\Anaconda2\lib\site-packages\backtrader\stores\oandastore.py", line 335, in _t_streaming_listener
  self._transaction(trans)
File "C:\Users\Gustav\Anaconda2\lib\site-packages\backtrader\stores\oandastore.py", line 565, in _transaction
   ttype = trans['type']
KeyError: u'type'
```
and
```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Users\Gustav\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\Gustav\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Gustav\Anaconda2\lib\site-packages\backtrader\stores\oandastore.py", line 548, in _t_order_cancel
    if oref is None:
NameError: global name 'oref' is not defined
```

This happens both with the sample Oanda code from the source and with a basic strategy using Oanda to trade and as the data-provider.

**Comment by pythonbacktrader** [comment]
I figured out main issue with Oanda for me. The Oandapy libary that backtrader is based on only supports the V1 API, however they have developed a V20 REST API now that seems much simpler and all new users on Oanda can only create accounts with the new API. 

However you can request Oanda to create a legacy sub-account for you on their livechat and thus use the old API.

**Comment by mementum** [comment]
The Oanda API v20 has no support for `Streaming` neither for Prices nor for events. See here: http://developer.oanda.com/rest-live/api-comparison/

And it is therefore basically unsuitable for anything. There is also confusing information on that page with regards historical prices when looking at `Candle Data` and `Intervals Supported`

This was already discussed here #106

Best regards

**Comment by mementum** [comment]
Readme updated to indicate v20 is not supported
