### ISSUE TITLE
Multi-threading with pool

### ISSUE THREAD

**Issue by kszynkar** [mementum/backtrader#153]
Hi mementum,

I would greatly appreciate your help. I tried your last "Let's Optimize" example in [http://backtrader.readthedocs.io/en/latest/quickstart/quickstart.html#let-s-optimize](url). 

When I run it, I get the following error:
```
Traceback (most recent call last):
  File "C:/Users/kszynkarczuk_stm/PycharmProjects/Hello World BackTrader/src/backtradertest.py", line 147, in <module>
    cerebro.run()
  File "C:\Anaconda3\envs\py34\lib\site-packages\backtrader\cerebro.py", line 739, in run
    self.runstrats = list(pool.map(self, iterstrats))
  File "C:\Anaconda3\envs\py34\lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Anaconda3\envs\py34\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
  File "C:\Anaconda3\envs\py34\lib\multiprocessing\pool.py", line 385, in _handle_tasks
    put(task)
  File "C:\Anaconda3\envs\py34\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "C:\Anaconda3\envs\py34\lib\multiprocessing\reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
```

When I change the code slightly adding `cerebro.p.maxcpus = 2` to only use one processor and avoid using the `pool.map` method, the code works for me.

I did some reading about this issue, and it looks like it may be because the Cerebro class is not picklable? Or might there be something wrong with my setup?

I'm running Python 3.4.5 and Windows 7.

Thanks
Kamil

**Comment by mementum** [comment]
It's not actually `Cerebro` but the *data feeds* which have an open file descriptor which with Python `3.4` (and at least also `3.5`) cannot be pickled.

Python `2.7` doesn't exhibit the same.

The actual behavior is a side effect of an optimization added following a request in #135 to avoid re-loading the datas over and over again in subprocesses.

There is no actual need to pass the open file descriptor because it is never used again.

In the meanwhile you can do the following:

```python
cerebro.run(optdatas=False)
```

And data will not be preloaded before breaking down into processes

**Comment by kszynkar** [comment]
Thank you sir!
