### ISSUE TITLE
Getting exception in Thread-3 when testing range strategies

### ISSUE THREAD

**Issue by xnox** [mementum/backtrader#159]
I am testing a range of strategies, randing a takeprofit parameter range(1,20). And thread-3 errors out for me

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 429, in _handle_results
    task = get()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'AutoInfoClass_pl_LineSeries_pl_LineIterator_pl_DataAccessor_pl_ObserverBase_pl_Observer_pl_DataTrades_5eee19a4c5cf4121bfbc137e0b521d04' on <module 'backtrader.metabase' from '/home/xnox/.local/lib/python3.5/site-packages/backtrader/metabase.py'>
```

This did not used to happen before. Something is wrong with my data?

**Comment by xnox** [comment]
Nah, bug in my code trying to access non-existant property.
