### ISSUE TITLE
errors in the plotting using matplotlib-1.3.1

### ISSUE THREAD

**Issue by OpenTrading** [mementum/backtrader#17]
I'm getting 3 different errors in the plotting using matplotlib-1.3.1
and python-2.7.10 under linux. The first one is:

```
cd docs
python observers-default.py
Traceback (most recent call last):
  File "observers-default.py", line 35, in <module>
    cerebro.plot()
  File "/t/lib/python2.7/site-packages/backtrader-1.1.5.88-py2.7.egg/backtrader/cerebro.py", line 227, in plot
    plotter.plot(strat, numfigs=numfigs)
  File "/t/lib/python2.7/site-packages/backtrader-1.1.5.88-py2.7.egg/backtrader/plot/plot.py", line 159, in plot
    self.plotdata(data, self.dplotsover[data])
  File "/t/lib/python2.7/site-packages/backtrader-1.1.5.88-py2.7.egg/backtrader/plot/plot.py", line 599, in plotdata
    prop=self.pinf.prop, numpoints=1, ncol=1)
  File "/usr/lib/python2.7/site-packages/matplotlib/axes.py", line 4778, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/legend.py", line 366, in __init__
    self._init_legend_box(handles, labels)
  File "/usr/lib/python2.7/site-packages/matplotlib/legend.py", line 630, in _init_legend_box
    handlebox)
TypeError: 'LineOnClosePlotHandler' object is not callable
```

**Comment by mementum** [comment]
The documentation states that the platform works with Matplotlib >= 1.4.1

http://backtrader.readthedocs.org/en/latest/installation.html
