### ISSUE TITLE
Failures to connect to live IB feed

### ISSUE THREAD

**Issue by rterbush** [mementum/backtrader#243]
I've been seeing this failed connection relatively frequently when starting the system. I've collected the following info at startup which seems to be what is triggering the disconnect.

Note that the last tick values sent are `0.0`.

This also is only triggered if I have a mix of both `.resampledata()` and `.replaydata()` on the two data feeds that are configured.

```
<tickPrice tickerId=16777218, field=1, price=-1.0, canAutoExecute=1>
<tickSize tickerId=16777218, field=0, size=0>
<tickPrice tickerId=16777218, field=2, price=-1.0, canAutoExecute=1>
<tickSize tickerId=16777218, field=3, size=0>
<tickSize tickerId=16777218, field=0, size=0>
<tickSize tickerId=16777218, field=3, size=0>
<tickPrice tickerId=16777218, field=9, price=226.53, canAutoExecute=0>
<tickPrice tickerId=16777219, field=1, price=2266.0, canAutoExecute=1>
<tickSize tickerId=16777219, field=0, size=3>
<tickPrice tickerId=16777219, field=2, price=2266.0, canAutoExecute=1>
<tickSize tickerId=16777219, field=3, size=9>
<tickPrice tickerId=16777219, field=4, price=2266.0, canAutoExecute=0>
<tickSize tickerId=16777219, field=5, size=5>
<tickSize tickerId=16777219, field=0, size=3>
<tickSize tickerId=16777219, field=3, size=9>
<tickSize tickerId=16777219, field=5, size=5>
<tickSize tickerId=16777219, field=8, size=99029>
<tickPrice tickerId=16777219, field=6, price=2270.5, canAutoExecute=0>
<tickPrice tickerId=16777219, field=7, price=2265.0, canAutoExecute=0>
<tickPrice tickerId=16777219, field=9, price=2272.5, canAutoExecute=0>
<tickPrice tickerId=16777219, field=14, price=2270.25, canAutoExecute=0>
<tickString tickerId=16777219, tickType=45, value=1484589596>
<tickGeneric tickerId=16777219, tickType=49, value=0.0>
<tickGeneric tickerId=16777219, tickType=49, value=0.0>
Traceback (most recent call last):
  File "systems/tests/test-replay-resample.py", line 172, in <module>
    cerebro.run()
  File "/home/inmate/.virtualenvs/backtrader3/lib/python3.4/site-packages/backtrader/cerebro.py", line 809, in run
    runstrat = self.runstrategies(iterstrat)
  File "/home/inmate/.virtualenvs/backtrader3/lib/python3.4/site-packages/backtrader/cerebro.py", line 933, in runstrategies
    self._runnext(runstrats)
  File "/home/inmate/.virtualenvs/backtrader3/lib/python3.4/site-packages/backtrader/cerebro.py", line 1166, in _runnext
    dt0 = min((d for i, d in enumerate(dts)
ValueError: min() arg is an empty sequence
```

I've managed to cause this behavior with the following simplified system code.:
```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import datetime as dt
import os.path
import sys
import pandas as pd
import pytz

# Import the backtrader platform
import backtrader as bt
import backtrader.feeds as btfeeds

EST = pytz.timezone('US/Eastern')
CST = pytz.timezone('US/Central')

# Create a Stratey
class TestStrategy(bt.Strategy):
    params = (
        ('maperiod', 15),
    )

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.datetime(tz=EST)
        print('%s, %s' % (dt.isoformat(), txt))
        if len(self.datas) > 1:
            dt = dt or self.datas[0].datetime.datetime(tz=CST)
            print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        self.dataclose = self.datas[0].close

        # To keep track of pending orders and buy price/commission
        self.order = None
        self.buyprice = None
        self.buycomm = None
        self.datastatus = False

        # Add a MovingAverageSimple indicator
        self.sma = bt.indicators.MovingAverageSimple(self.datas[0], period=self.params.maperiod)

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enougth cash
        if order.status in [order.Completed, order.Canceled, order.Margin]:
            if order.isbuy():
                self.log(
                    'BUY EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                    (order.executed.price,
                     order.executed.value,
                     order.executed.comm))

                self.buyprice = order.executed.price
                self.buycomm = order.executed.comm
            else:  # Sell
                self.log('SELL EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                         (order.executed.price,
                          order.executed.value,
                          order.executed.comm))

            self.bar_executed = len(self)

        # Write down: no pending order
        self.order = None

    def notify_data(self, data, status, *args, **kwargs):
        if len(data._name) > 0:
            fname = data._name
        else:
            fname = data.contract.m_symbol

        print('*' * 3, '%s DATA NOTIF: %s %s' %
              (dt.datetime.now().strftime('%Y-%m-%dT%H:%M:%S'),
               fname, data._getstatusname(status)), *args)

        if status == data.LIVE:
            self.datastatus = True

    def notify_trade(self, trade):
        if not trade.isclosed:
            return

        self.log('OPERATION PROFIT, GROSS %.2f, NET %.2f' %
                 (trade.pnl, trade.pnlcomm))

    def next(self):
        # Simply log the closing price of the series from the reference
        self.log('Close, %.2f' % self.dataclose[0])

        # Check if an order is pending ... if yes, we cannot send a 2nd one
        if self.order:
            return

        # Check if we are in the market
        if not self.position:

            # Not yet ... we MIGHT BUY if ...
            if self.dataclose[0] > self.sma[0]:
                # current close less than previous close

                # BUY, BUY, BUY!!! (with default parameters)
                self.log('BUY CREATE, %.2f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.buy()

        else:

            # Already in the market ... we might sell
            if self.dataclose[0] < self.sma[0]:
                # SELL, SELL, SELL!!! (with all possible default parameters)
                self.log('SELL CREATE, %.2f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()


if __name__ == '__main__':
    # Create a cerebro entity
    cerebro = bt.Cerebro()

    # Add a strategy
    cerebro.addstrategy(TestStrategy)

    # Datas are in a subfolder of the samples. Need to find where the script is
    # because it could have been called from anywhere
    modpath = os.path.dirname(os.path.abspath(sys.argv[0]))

    # Parse CSI SPY data file
    # staticdata0path = os.path.join(modpath, '../../datas/SPY-yahoo.csv')
    # staticdata0 = btfeeds.YahooFinanceCSVData(dataname=staticdata0path)
    staticdata0path = os.path.join(modpath, '../../datas/SPY.CSV')

    staticdata0frame = pd.read_csv(staticdata0path,
                                   header=0,
                                   skiprows=0,
                                   parse_dates=True,
                                   index_col=0)
    staticdata0 = bt.feeds.PandasData(dataname=staticdata0frame)

#    import pdb; pdb.set_trace()

    storekwargs = dict(
        host='127.0.4.1',
        port=7465,
        clientId=90,
        timeoffset=True,
        reconnect=3,
        timeout=3,
        _debug=True
    )

    ibstore = bt.stores.IBStore(**storekwargs)

    broker = ibstore.getbroker()

    cerebro.setbroker(broker)

    # NQ Live Data
    data0 = ibstore.getdata(dataname='NQ-201703-GLOBEX-USD',
                            timeframe=bt.TimeFrame.Days, compression=1,
                            sessionstart=dt.time(8,30), sessionend=dt.time(15, 15))
    cerebro.replaydata(data0, timeframe=bt.TimeFrame.Days, compression=1)

    # ES Live Data
    data1 = ibstore.getdata(dataname='ES-201703-GLOBEX-USD', backfill_from=staticdata0,
                            timeframe=bt.TimeFrame.Days, compression=1,
                            sessionstart=dt.time(8,30), sessionend=dt.time(15, 15))
    cerebro.resampledata(data1, timeframe=bt.TimeFrame.Days, compression=1)

    # Add a FixedSize sizer according to the stake
    cerebro.addsizer(bt.sizers.FixedSize, stake=1)

    # Set the commission - 0.1% ... divide by 100 to remove the %
    cerebro.broker.setcommission(commission=0.001)

    # Print out the starting conditions
    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

    # Run over everything
    cerebro.run()

    # Print out the final result
    print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
```

**Comment by mementum** [comment]
May this be the cause?

> - The data with the smallest timeframe (and thus the larger number of bars) must be the 1st one to be added to the Cerebro instance

https://www.backtrader.com/docu/data-multitimeframe/data-multitimeframe.html?highlight=smaller%20timeframe

**Comment by rterbush** [comment]
I've updated the code above as I was incorrectly trying to resample to a faster timeframe than the original feed.

I've corrected to make the Minutes timeframe the first loaded data followed by the daily timeframe.

The difference is if I make one of these `.replaydata()` and the other `.resampledata()`, the script fails at the start.

Is it true that even if the instrument is different, the shorter timeframe data must be loaded first?

**Comment by mementum** [comment]
> Is it true that even if the instrument is different, the shorter timeframe data must be loaded first?

Not any longer. This should have been in the code already a long time ago.

> The difference is if I make one of these .replaydata() and the other .resampledata(), the script fails at the start.

Regardless of which one you were replaying / resampling?

**Comment by rterbush** [comment]
Crashes created:

1. NQ first, resampledata(), with backfill_from, ES second, replaydata(), without backfill_from

2. NQ first, replaydata(), without backfill_from, ES second, resampledata(), with backfill_from

3. NQ second, replaydata(), without backfill_from, ES first, resampledata(), with backfill_from

4. NQ second, resampledata(), with backfill_from, ES first, replaydata(), without backfill_from

So it seems to boil down to as follows:

**Mix of both resampledata() and replaydata() with the replaydata() feed missing a backfill_from= and the resampledata() having a backfill_from.**

**If neither datafeed has a `backfill_from`, there is no problem.**

I've changed the code above to reflect the most recent use case that fails.

**Comment by mementum** [comment]
The core architecture will have to be revamped to support `replay` in mix use cases. Before the `1.9.x` series, the data feeds would not **paused** (pointer moved backwards) to wait for the others. With the naive assumption that people would not be mixing assets with different trading calendars.

Introducing that has the side effect that `replay` cannot cope with the pointers movement, because it is always delivering.

At the moment there is no good solution that can be explored.
