### ISSUE TITLE
IBData is not initialized properly in historical mode

### ISSUE THREAD

**Issue by shaoupipi** [mementum/backtrader#244]
When i used IBData to get historical data,  the sample code can't be execute correctly. 
"todate" or other parameters may be not initialized properly in IBData._st_start() 

```
Server Version: 76
TWS Time at connection:20170117 01:43:18 EST
Traceback (most recent call last):
  File "/home/shaou/quant/pycharm-2016.3.1/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/shaou/quant/pycharm-2016.3.1/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/shaou/quant/pycharm-2016.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/shaou/quant/WinTraderV3/test2.py", line 155, in <module>
    cerebro.run()
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/cerebro.py", line 809, in run
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/cerebro.py", line 870, in runstrategies
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/feed.py", line 154, in _start
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/feeds/ibdata.py", line 360, in start
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/feeds/ibdata.py", line 546, in _st_start
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/lineseries.py", line 429, in __getattr__
AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_Abst' object has no attribute 'todate'
```

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import datetime
import pytz
from time import sleep

import backtrader as bt
from backtrader.utils import flushfile  # win32 quick stdout flushing

Ignore_IB_Error = [2104, 2106]

class IBStrategy(bt.Strategy):

    def notify_data(self, data, status, *args, **kwargs):
        print('*' * 5, 'DATA NOTIF:', data._getstatusname(status), *args)

    def notify_store(self, msg, *args, **kwargs):
        if(args[1] in Ignore_IB_Error):
            pass
        else:
            print('*' * 5, 'STORE NOTIF:', msg)

    def notify_order(self, order):
        if order.status in [order.Completed, order.Cancelled, order.Rejected]:
            self.order = None

        print('-' * 50, 'ORDER BEGIN', datetime.datetime.now())
        print(order)
        print('-' * 50, 'ORDER END')

    def notify_trade(self, trade):
        print('-' * 50, 'TRADE BEGIN', datetime.datetime.now())
        print(trade)
        print('-' * 50, 'TRADE END')

    def prenext(self):
        print("enter prenext()")

    def next(self, frompre=False):
        print('enter next()')
        txt = list()
        txt.append('Data0')
        txt.append('%04d' % len(self.data0))
        dtfmt = '%Y-%m-%dT%H:%M:%S.%f'
        txt.append('{}'.format(self.data.datetime[0]))
        txt.append('%s' % self.data.datetime.datetime(0).strftime(dtfmt))
        txt.append('{}'.format(self.data.open[0]))
        txt.append('{}'.format(self.data.high[0]))
        txt.append('{}'.format(self.data.low[0]))
        txt.append('{}'.format(self.data.close[0]))
        txt.append('{}'.format(self.data.volume[0]))
        print(', '.join(txt))

    def start(self):
        print('enter start()')

if __name__ == '__main__':
    cerebro = bt.Cerebro()
    cerebro.broker = bt.brokers.IBBroker(host='127.0.0.1', port=7496, clientId=1)
    data = bt.feeds.IBData(dataname='AAPL-STK-SMART',
                           historical=True,
                           what = 'TRADES',
                           tz=pytz.timezone('US/Eastern'),
                           fromdate=datetime.datetime(2016, 12, 28, 9, 30, 0),
                           todate=datetime.datetime(2016, 12, 28, 16, 0, 0),
                           timeframe=bt.TimeFrame.Seconds,
                           compression=1)
    cerebro.adddata(data)
    cerebro.addstrategy(IBStrategy)
    cerebro.run()
```

**Comment by mementum** [comment]
Have you tried to initialize the `IBStore` and fetch the data with the `getdata` method ? (and `getbroker` for the broker)

**Comment by shaoupipi** [comment]
I have tried to initialize the  IBStore and fetch the data with the getdata method, the same problem exists: 

Server Version: 76
TWS Time at connection:20170121 21:25:17 EST
Traceback (most recent call last):
  File "/home/shaou/quant/pycharm-2016.3.1/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/shaou/quant/pycharm-2016.3.1/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/shaou/quant/pycharm-2016.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/shaou/quant/WinTraderV3/test3.py", line 128, in <module>
    cerebro.run()
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/cerebro.py", line 809, in run
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/cerebro.py", line 870, in runstrategies
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/feed.py", line 157, in _start
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/feeds/ibdata.py", line 360, in start
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/feeds/ibdata.py", line 546, in _st_start
  File "/home/shaou/anaconda3/lib/python3.5/site-packages/backtrader-1.9.24.105-py3.5.egg/backtrader/lineseries.py", line 429, in __getattr__
AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_Abst' object has no attribute 'todate'

if __name__ == '__main__':

    ibstore = bt.stores.IBStore(host='127.0.0.1', port=7496, clientId=35)

    data0 = ibstore.getdata(dataname='AAPL-STK-SMART',
                            historical=True,
                            what='TRADES',
                            tz=pytz.timezone('US/Eastern'),
                            fromdate=datetime.datetime(2017, 1, 20, 9, 30, 0),
                            todate=datetime.datetime(2017, 1, 20, 16, 0, 0),
                            timeframe=bt.TimeFrame.Minutes,
                            compression=1)

    data1 = ibstore.getdata(dataname='QCOM-STK-SMART',
                            historical=True,
                            what='TRADES',
                            tz=pytz.timezone('US/Eastern'),
                            fromdate=datetime.datetime(2017, 1, 20, 9, 30, 0),
                            todate=datetime.datetime(2017, 1, 20, 16, 0, 0),
                            timeframe=bt.TimeFrame.Minutes,
                            compression=1)

    cerebro = bt.Cerebro()
    cerebro.broker = ibstore.getbroker()
    cerebro.adddata(data0)
    cerebro.adddata(data1)
    cerebro.addstrategy(IBStrategy)
    cerebro.run()
