### ISSUE TITLE
About pandas data feed--No atrribute "_barstack" error

### ISSUE THREAD

**Issue by allisnone** [mementum/backtrader#27]
Source code:

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse

import backtrader as bt
#import backtrader.feeds as btfeeds

import pandas

# Create a Stratey
class TestStrategy(bt.Strategy):

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close

    def next(self):
        # Simply log the closing price of the series from the reference
        self.log('Close, %.2f' % self.dataclose[0])

def runstrat():
    args = parse_args()

    # Create a cerebro entity
    cerebro = bt.Cerebro(stdstats=False)

    # Add a strategy
    cerebro.addstrategy(TestStrategy)

    # Get a pandas dataframe
    datapath = ('./update/002678.csv')

    # Simulate the header row isn't there if noheaders requested
    skiprows = 1 if args.noheaders else 0
    header = None if args.noheaders else 0

    dataframe = pandas.read_csv(datapath,
                                skiprows=skiprows,
                                header=header,
                                parse_dates=True,
                                index_col=0)
    dataframe.index.name='date'

    if not args.noprint:
        print('--------------------------------------------------')
        print(dataframe)
        print('--------------------------------------------------')
    
    dataframe[str('openinterest')]=0.0
    print ("dataframe with openinterest column:")
    print(dataframe)

    # Pass it to the backtrader datafeed and add it to the cerebro
    data = bt.feeds.PandasData(dataname=dataframe)
   

    cerebro.adddata(data)

    # Run over everything
    cerebro.run()

    # Plot the result
    cerebro.plot(style='bar')

def parse_args():
    parser = argparse.ArgumentParser(
        description='Pandas test script')

    parser.add_argument('--noheaders', action='store_true', default=False,
                        required=False,
                        help='Do not use header rows')

    parser.add_argument('--noprint', action='store_true', default=False,
                        help='Print the dataframe')

    return parser.parse_args()

if __name__ == '__main__':
    runstrat()

Console logs:

--------------------------------------------------
             open   high    low  close    volume
date                                            
2012-05-31   8.22   8.75   8.10   8.67  30079116
2012-06-01   8.56   8.65   8.35   8.41  15404456
2012-06-04   8.11   8.22   7.91   7.99  13976228
2012-06-05   8.04   8.11   7.74   7.84   9429878
2012-06-06   7.86   8.10   7.81   7.86   9295149
2012-06-07   7.95   8.00   7.59   7.60   9650608
2012-06-08   7.65   7.77   7.31   7.34   8362199
2012-06-11   7.34   7.45   7.00   7.23   9060132
2012-06-12   7.10   7.36   7.03   7.15   7887191
2012-06-13   7.13   7.33   7.03   7.29   7200503
2012-06-14   7.21   7.48   7.06   7.31   8204100
2012-06-15   7.31   7.34   7.11   7.19   5430351
2012-06-18   7.24   7.57   7.16   7.42   7272989
2012-06-19   7.33   7.40   7.26   7.34   5506595
2012-06-20   7.37   7.59   7.32   7.44   6988527
2012-06-21   7.40   7.44   7.22   7.38   4771320
2012-06-26   7.11   7.22   6.81   7.18   4752317
2012-06-27   7.16   7.39   7.08   7.14   4004544
2012-06-28   7.18   7.23   7.01   7.06   3642727
2012-06-29   7.01   7.38   6.91   7.27   6222782
2012-07-02   7.28   7.38   7.20   7.30   3948016
2012-07-03   7.29   7.68   7.26   7.51   7414848
2012-07-04   7.46   7.54   7.31   7.41   4564094
2012-07-05   7.36   7.37   7.16   7.17   4052037
2012-07-06   7.21   7.32   6.99   7.29   4986092
2012-07-09   7.20   7.21   7.03   7.08   4544633
2012-07-10   7.06   7.10   6.90   6.92   3177994
2012-07-11   6.94   7.05   6.88   6.92   2225550
2012-07-12   6.92   7.20   6.75   6.96   5851250
2012-07-13   6.91   6.98   6.77   6.81   3211387
...           ...    ...    ...    ...       ...
2015-09-07  13.00  13.63  11.75  11.85  18096736
2015-09-08  11.85  12.77  11.33  12.71   8744236
2015-09-09  12.80  13.40  12.58  13.05  31850402
2015-09-10  12.71  13.17  12.55  12.58  11725032
2015-09-11  12.50  13.01  12.45  12.81  10912332
2015-09-14  13.35  13.62  11.53  11.57  18329411
2015-09-15  11.00  11.24  10.41  10.41  11810127
2015-09-16  10.48  11.45  10.32  11.35  13188209
2015-09-17  11.24  11.81  10.80  10.85  14307093
2015-09-18  10.81  11.13  10.50  10.86   8860591
2015-09-21  10.66  11.54  10.40  11.51   9958687
2015-09-22  11.51  11.78  11.35  11.63  11518074
2015-09-23  11.30  11.70  11.18  11.46   8674480
2015-09-24  11.46  11.75  11.41  11.60   8283291
2015-09-25  11.69  12.59  11.59  12.05  17357389
2015-09-28  12.21  12.95  11.40  12.78  15825431
2015-09-29  12.30  13.62  12.15  13.07  22859025
2015-09-30  12.83  13.06  12.16  12.41  12173671
2015-10-08  12.79  13.34  12.55  12.95  11770620
2015-10-09  12.80  13.15  12.57  12.88   9829004
2015-10-12  13.12  13.80  13.01  13.77  15049190
2015-10-13  13.55  14.56  13.45  13.85  13474511
2015-10-14  13.65  13.97  13.22  13.29  11928528
2015-10-15  13.37  14.25  13.37  13.99  13499485
2015-10-16  14.22  14.94  13.61  14.67  18536864
2015-10-19  14.63  16.14  14.25  16.14  23703625
2015-10-20  15.86  17.36  15.54  16.47  23555586
2015-10-21  16.23  17.51  14.95  14.95  23663628
2015-10-22  15.23  16.14  15.05  15.90  18974725
2015-10-23  15.92  17.49  15.92  17.49  19737205

[808 rows x 5 columns]
--------------------------------------------------
dataframe with openinterest column:
             open   high    low  close    volume  openinterest
date                                                          
2012-05-31   8.22   8.75   8.10   8.67  30079116             0
2012-06-01   8.56   8.65   8.35   8.41  15404456             0
2012-06-04   8.11   8.22   7.91   7.99  13976228             0
2012-06-05   8.04   8.11   7.74   7.84   9429878             0
2012-06-06   7.86   8.10   7.81   7.86   9295149             0
2012-06-07   7.95   8.00   7.59   7.60   9650608             0
2012-06-08   7.65   7.77   7.31   7.34   8362199             0
2012-06-11   7.34   7.45   7.00   7.23   9060132             0
2012-06-12   7.10   7.36   7.03   7.15   7887191             0
2012-06-13   7.13   7.33   7.03   7.29   7200503             0
2012-06-14   7.21   7.48   7.06   7.31   8204100             0
2012-06-15   7.31   7.34   7.11   7.19   5430351             0
2012-06-18   7.24   7.57   7.16   7.42   7272989             0
2012-06-19   7.33   7.40   7.26   7.34   5506595             0
2012-06-20   7.37   7.59   7.32   7.44   6988527             0
2012-06-21   7.40   7.44   7.22   7.38   4771320             0
2012-06-26   7.11   7.22   6.81   7.18   4752317             0
2012-06-27   7.16   7.39   7.08   7.14   4004544             0
2012-06-28   7.18   7.23   7.01   7.06   3642727             0
2012-06-29   7.01   7.38   6.91   7.27   6222782             0
2012-07-02   7.28   7.38   7.20   7.30   3948016             0
2012-07-03   7.29   7.68   7.26   7.51   7414848             0
2012-07-04   7.46   7.54   7.31   7.41   4564094             0
2012-07-05   7.36   7.37   7.16   7.17   4052037             0
2012-07-06   7.21   7.32   6.99   7.29   4986092             0
2012-07-09   7.20   7.21   7.03   7.08   4544633             0
2012-07-10   7.06   7.10   6.90   6.92   3177994             0
2012-07-11   6.94   7.05   6.88   6.92   2225550             0
2012-07-12   6.92   7.20   6.75   6.96   5851250             0
2012-07-13   6.91   6.98   6.77   6.81   3211387             0
...           ...    ...    ...    ...       ...           ...
2015-09-07  13.00  13.63  11.75  11.85  18096736             0
2015-09-08  11.85  12.77  11.33  12.71   8744236             0
2015-09-09  12.80  13.40  12.58  13.05  31850402             0
2015-09-10  12.71  13.17  12.55  12.58  11725032             0
2015-09-11  12.50  13.01  12.45  12.81  10912332             0
2015-09-14  13.35  13.62  11.53  11.57  18329411             0
2015-09-15  11.00  11.24  10.41  10.41  11810127             0
2015-09-16  10.48  11.45  10.32  11.35  13188209             0
2015-09-17  11.24  11.81  10.80  10.85  14307093             0
2015-09-18  10.81  11.13  10.50  10.86   8860591             0
2015-09-21  10.66  11.54  10.40  11.51   9958687             0
2015-09-22  11.51  11.78  11.35  11.63  11518074             0
2015-09-23  11.30  11.70  11.18  11.46   8674480             0
2015-09-24  11.46  11.75  11.41  11.60   8283291             0
2015-09-25  11.69  12.59  11.59  12.05  17357389             0
2015-09-28  12.21  12.95  11.40  12.78  15825431             0
2015-09-29  12.30  13.62  12.15  13.07  22859025             0
2015-09-30  12.83  13.06  12.16  12.41  12173671             0
2015-10-08  12.79  13.34  12.55  12.95  11770620             0
2015-10-09  12.80  13.15  12.57  12.88   9829004             0
2015-10-12  13.12  13.80  13.01  13.77  15049190             0
2015-10-13  13.55  14.56  13.45  13.85  13474511             0
2015-10-14  13.65  13.97  13.22  13.29  11928528             0
2015-10-15  13.37  14.25  13.37  13.99  13499485             0
2015-10-16  14.22  14.94  13.61  14.67  18536864             0
2015-10-19  14.63  16.14  14.25  16.14  23703625             0
2015-10-20  15.86  17.36  15.54  16.47  23555586             0
2015-10-21  16.23  17.51  14.95  14.95  23663628             0
2015-10-22  15.23  16.14  15.05  15.90  18974725             0
2015-10-23  15.92  17.49  15.92  17.49  19737205             0

[808 rows x 6 columns]
Traceback (most recent call last):
  File "E:\work\stockAnalyze\back_trader.py", line 88, in <module>
    runstrat()
  File "E:\work\stockAnalyze\back_trader.py", line 67, in runstrat
    cerebro.run()
  File "C:\Python32\lib\site-packages\backtrader\cerebro.py", line 370, in run
    runstrat = self.runstrategies(iterstrat)
  File "C:\Python32\lib\site-packages\backtrader\cerebro.py", line 439, in runstrategies
    data.preload()
  File "C:\Python32\lib\site-packages\backtrader\feed.py", line 232, in preload
    while self.load():
  File "C:\Python32\lib\site-packages\backtrader\feed.py", line 259, in load
    if self._fromstack():  # bar is available
  File "C:\Python32\lib\site-packages\backtrader\feed.py", line 335, in _fromstack
    if self._barstack:
  File "C:\Python32\lib\site-packages\backtrader\lineseries.py", line 407, in __getattr__
    return getattr(self.lines, name)
AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_AbstractDataBase_DataBase_PandasData' object has no attribute '_barstack'

**Comment by allisnone** [comment]
I am new user about backtrader. May sombody help on these issue? Thanks!

**Comment by allisnone** [comment]
Grate! Thanks you quick correction. And I found a little bug for python2.7:  pandanfeed.py(line 165)-->class PandasData-->__init__:  cstrings = filter(lambda x: isinstance(x, string_types), colnames);  the error will be there as "TypeError: object of type 'itertools.ifilter' has no len()".
After  changed this line as following in python2.7: cstrings = list(filter(lambda x: isinstance(x, string_types), colnames)), then fixed.

**Comment by mementum** [comment]
Thank you for the heads up. It's a leftover from the removal of six as a dependency, It would have kicked in Python 3 too.
