### ISSUE TITLE
cerebro.plot() failed to plot diagram with no indicators

### ISSUE THREAD

**Issue by ab-trader** [mementum/backtrader#294]
Received the following error message:
```
Traceback (most recent call last):
  File "etf_viewer.py", line 61, in <module>
    cerebro.plot()
  File "D:\Python27\lib\site-packages\backtrader\cerebro.py", line 659, in plot
    start=start, end=end)
  File "D:\Python27\lib\site-packages\backtrader\plot\plot.py", line 218, in plot
    self.plotdata(data, self.dplotsover[data])
  File "D:\Python27\lib\site-packages\backtrader\plot\plot.py", line 671, in plotdata
    vtags = ind.plotinfo._get('plotvaluetags', True)
UnboundLocalError: local variable 'ind' referenced before assignment
```

Simply called `cerebro.plot()`, no indicators, only data feeds, used `stdstats=False`, release 1.9.38.116

**Comment by mementum** [comment]
Wrong code clearly. The problem being that things are working in the test environment. Looking for the root cause of the testing failure to catch such a simple error.

**Comment by mementum** [comment]
Commit 130ef6b745317197173e1967007116f4c072e63b

Testing should also be done with something without indicators/observers et al.
