### ISSUE TITLE
Problem using Oanda broker in 1.9.52.121

### ISSUE THREAD

**Issue by 0x74-0x62** [mementum/backtrader#323]
I use backtrader 1.9.52.121 and try to use Oanda as live broker:

```
oanda_store = bt.stores.OandaStore(token='TOKEN',
                              account='ACCOUNT',
                              practice=True)

cerebro.setbroker(oanda_store.getbroker())

data = oanda_store.getdata(dataname='EUR_USD',
                              compression=1,
                              backfill=False,
                              qcheck=0.5,
                              timeframe=bt.TimeFrame.Minutes,
                              backfill_start=False,
                              historical=False)
```

When calling cerebro.run(), the following problem occurs:

```
Traceback (most recent call last):
  File "trader.py", line 99, in <module>
    trader_main()
  File "trader.py", line 93, in trader_main
    cerebro.run()
  File "[...]/python3.5/site-packages/backtrader/cerebro.py", line 1073, in run
    runstrat = self.runstrategies(iterstrat)
  File "[...]/python3.5/site-packages/backtrader/cerebro.py", line 1235, in runstrategies
    self._runnext(runstrats)
  File "[...]/python3.5/site-packages/backtrader/cerebro.py", line 1560, in _runnext
    strat._next()
  File "[...]/python3.5/site-packages/backtrader/strategy.py", line 324, in _next
    super(Strategy, self)._next()
  File "[...]/python3.5/site-packages/backtrader/lineiterator.py", line 247, in _next
    self._notify()
  File "[...]/python3.5/site-packages/backtrader/strategy.py", line 580, in _notify
    fundvalue = self.broker.fundvalue
AttributeError: 'OandaBroker' object has no attribute 'fundvalue'
```

Could this problem be related to the new fund feature? Or am I doing something wrong? Using just the Oanda data feed without the Oanda broker works without problems.

**Comment by mementum** [comment]
It is related. It  has only been tested with the simulation broker, because it is the only one for which it makes sense.

To be corrected soon

Thanks for the report
