### ISSUE TITLE
LinesOperations on Resampled data fails

### ISSUE THREAD

**Issue by kunalpawaskar** [mementum/backtrader#82]
First, thanks @mementum for creating this. I have found it very useful. Exploring it at the moment.

I faced a couple of issues that you may be able to understand:

1 - If I do not prefix `self.` to any indicator for example like:

`self.slowema_large_tf = btind.SMA(self.data1, period=self.p.fastperiod)`

it is not accessible in next. This behaviour seemed different compared to the backtrader documentation.

2 - I am using Resampler.

```
def __init__(self):
        self.slowema_small_tf = btind.SMA(self.data, period=self.p.fastperiod)
        self.fastema_small_tf = btind.SMA(self.data, period=self.p.slowperiod

        self.slowema_large_tf = btind.SMA(self.data1, period=self.p.fastperiod)
        self.fastema_large_tf = btind.SMA(self.data1, period=self.p.slowperiod)

        atr_large_tf=btind.ATR(self.data1)

        self.reversal = self.slowema_large_tf -  self.fastema_large_tf
``` 

I get an error as follows:
```
Traceback (most recent call last):
  File "C:/Users/kunal.pawaskar/PycharmProjects/tryfile/try.py", line 184, in <module>
    runstrat()
  File "C:/Users/kunal.pawaskar/PycharmProjects/tryfile/try.py", line 145, in runstrat
    cerebro.run()
  File "D:\python base\lib\site-packages\backtrader\cerebro.py", line 385, in run
    runstrat = self.runstrategies(iterstrat)
  File "D:\python base\lib\site-packages\backtrader\cerebro.py", line 462, in runstrategies
    self._runonce(runstrats)
  File "D:\python base\lib\site-packages\backtrader\cerebro.py", line 544, in _runonce
    strat._once()
  File "D:\python base\lib\site-packages\backtrader\lineiterator.py", line 248, in _once
    indicator._once()
  File "D:\python base\lib\site-packages\backtrader\linebuffer.py", line 529, in _once
    self.once(self._minperiod, self.buflen())
  File "D:\python base\lib\site-packages\backtrader\linebuffer.py", line 642, in once
    self._once_op(start, end)
  File "D:\python base\lib\site-packages\backtrader\linebuffer.py", line 656, in _once_op
    dst[i] = op(srca[i], srcb[i])
IndexError: array index out of range
```

If I change the last line to:

`self.reversal = self.slowema_small_tf -  self.fastema_small_tf`

it works fine. 

In summary, using the larger timeframe causes a problem inside ``__init__``

3 -  Another problem was that when next(self) deals with the last line in the dataset (arbitrarily set to a certain date outer limit), it throws an error as follows:

```
Traceback (most recent call last):
  File "C:/Users/kunal.pawaskar/PycharmProjects/tryfile/try.py", line 184, in <module>
    runstrat()
  File "C:/Users/kunal.pawaskar/PycharmProjects/tryfile/try.py", line 145, in runstrat
    cerebro.run()
  File "D:\python base\lib\site-packages\backtrader\cerebro.py", line 385, in run
    runstrat = self.runstrategies(iterstrat)
  File "D:\python base\lib\site-packages\backtrader\cerebro.py", line 475, in runstrategies
    self.stop_writers(runstrats)
  File "D:\python base\lib\site-packages\backtrader\cerebro.py", line 490, in stop_writers
    stratinfos[stname] = strat.getwriterinfo()
  File "D:\python base\lib\site-packages\backtrader\strategy.py", line 308, in getwriterinfo
    sinfo[itname].Lines = item.lines.getlinealiases() or None
AttributeError: 'LinesOperation' object has no attribute 'lines'
```

Any help would be greatly appreciated.

**Comment by mementum** [comment]
*1* This is Python and even with metaclasses to alleviate some of the burden during construction/initialization there are things which cannot be overriden. If something is not kept as an attribute in a class instance (object), it cannot later be addressed.

  Any link to where the documentation may be wrong?

*2* This is a bug. It is of course that operations on lines have escaped the original intent (to be used inside *indicators*) and like in your case they even address datas of different lengths (different timeframes)

Fortunately I think this case can be luckily corrected with a small fix.

*3* This one cannot be looked into without understanding/seeing what you mean with "arbitrarily set to a certain date outer limit"

In any case if you are not using version `1.2.5.88` or later and seeing the `getwriterinfo` problem you may have hit issue #71, which was caused by the same "LinesOperations" expansion I just mentioned in 2.

**Comment by mementum** [comment]
This sample below contains your operations and runs successfully with the fix introduced in the development branch (which you can clone and use to test)

```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
###############################################################################
#
# Copyright (C) 2016 Daniel Rodriguez
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import datetime

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.indicators as btind
import backtrader.utils.flushfile


class St(bt.Strategy):
    params = (('fastperiod', 10), ('slowperiod', 30))

    def __init__(self):
        self.slowema_small_tf = btind.SMA(self.data, period=self.p.fastperiod)
        self.fastema_small_tf = btind.SMA(self.data, period=self.p.slowperiod)

        self.slowema_large_tf = btind.SMA(self.data1, period=self.p.fastperiod)
        self.fastema_large_tf = btind.SMA(self.data1, period=self.p.slowperiod)

        atr_large_tf = btind.ATR(self.data1)

        self.reversal = self.slowema_large_tf - self.fastema_large_tf

    def next(self):
        txt = ', '.join([
             '%04d' % len(self.data0),
             '%04d' % len(self.data1),
             self.data.datetime.date(0).isoformat(),
             '%.2f' % self.data.close[0],
             '%.2f' % self.data1.close[0]])

        print(txt)


def runstrat():
    args = parse_args()

    cerebro = bt.Cerebro()
    data = btfeeds.BacktraderCSVData(dataname=args.data)
    cerebro.adddata(data)
    cerebro.resampledata(data, timeframe=bt.TimeFrame.Weeks)

    cerebro.addstrategy(St)
    cerebro.run()
    if args.plot:
        cerebro.plot(style='bar')


def parse_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='Sample for pivot point and cross plotting')

    parser.add_argument('--data', required=False,
                        default='../../datas/2005-2006-day-001.txt',
                        help='Data to be read in')

    parser.add_argument('--plot', required=False, action='store_true',
                        help=('Plot the result'))

    return parser.parse_args()


if __name__ == '__main__':
    runstrat()
```

**Comment by kunalpawaskar** [comment]
Thanks @mementum for getting back quickly.

1. Documentation link where referencing object via "self." is not used:

http://backtrader.readthedocs.io/en/latest/concepts.html?highlight=sma2#stage-2-operators-true-to-nature

2. and 3 were solved with the fixes you provided.

**Comment by mementum** [comment]
Thanks for the indication. That's a blatant error in the docs.probably due to a search and replace which  removed `self`.

To be corrected.

**Comment by kunalpawaskar** [comment]
A fresh error was seen after I made the changes that you shared above.

For the following code:
```

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.indicators as btind
import datetime as dt

class SMAStrategy(bt.Strategy):
    params = (
        ('period', 5),
        ('onlydaily', False),
        ('fastperiod',4),
        ('slowperiod',9),
    )

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))


    def __init__(self):
        self.slowema_small_tf = btind.SMA(self.data, period=self.p.fastperiod)
        self.fastema_small_tf = btind.SMA(self.data, period=self.p.slowperiod)

        self.slowema_large_tf = btind.SMA(self.data1, period=self.p.fastperiod)
        self.fastema_large_tf = btind.SMA(self.data1, period=self.p.slowperiod)

        self.atr_large_tf=btind.ATR(self.data1)

        self.reversal=(self.fastema_large_tf*(2/(self.p.fastperiod+1)-1)-self.slowema_large_tf*(2/(self.p.slowperiod+1)-1))/((2/(self.p.fastperiod+1))-2/(self.p.slowperiod+1))


    def next(self):
        print('--------------------------------------------------')
        print('nextstart called with len', len(self))
        print('--------------------------------------------------')

        print(self.reversal)

        self.log('slowema: %.2f' % (self.slowema_large_tf[0]))
        self.log('fastema: %.2f' % (self.fastema_large_tf[0]))
        self.log('close: %.2f' % (self.data.close[0]))
        self.log('prev reversal: %.2f' % (self.reversal[0]))

def runstrat():

    # Create a cerebro entity
    cerebro = bt.Cerebro(stdstats=False)

    # Add a strategy
    cerebro.addstrategy(
    SMAStrategy,
    period=5,
    onlydaily=0,
    )
    # Load the Data

    data = btfeeds.GenericCSVData(
        dataname='C:/bt-datas/2006-min-005.txt',
        fromdate=dt.datetime(2006,1,2),
        todate=dt.datetime(2006,1,26),
        nullvalue=0.0,
        dtformat=('%Y-%m-%d'),
        tmformat=('%H:%M:%S'),
        datetime=0,
        time=1,
        open=2,
        high=3,
        low=4,
        close=5,
        volume=6,
        openinterest=7
    )

    data2 = bt.DataResampler(
        dataname=data,
        timeframe = bt.TimeFrame.Days,
        compression=1)

    # First add the original data - smaller timeframe
    cerebro.adddata(data)

    # And then the large timeframe
    cerebro.adddata(data2)

    # Run over everything
    cerebro.run()

    # Plot the result
    cerebro.plot(style='candlestick')


if __name__ == '__main__':
    runstrat()
```

 File "C:/Users/arbit/PycharmProjects/tryfile/abc3.py", line 48, in next
    self.log('prev reversal: %.2f' % (self.reversal[0]))
  File "D:\python base\lib\site-packages\backtrader\linebuffer.py", line 125, in __getitem__
    return self.array[self.idx + ago]
IndexError: array index out of range

I am attempting to use current value of reversal by using subcript [0].

Should not reversal be set up line a line object? If yes, I think that the intended behaviour should allow user to access present and earlier values in the Line?

Thanks.

**Comment by mementum** [comment]
The problem here is:

```
self.reversal=(self.fastema_large_tf*(2/(self.p.fastperiod+1)-1)-self.slowema_large_tf*(2/(self.p.slowperiod+1)-1))/((2/(self.p.fastperiod+1))-2/(self.p.slowperiod+1))
```

These are uncharted waters in that you are actually creating an on-the-fly indicator (a _lines object_) which mixes previous _lines objects_ operating on different timeframes.

Below the surface you are mixing _lines objects_ which have different lengths and this is for sure wreaking havoc.

To be looked into.

**Comment by mementum** [comment]
Disregard the previous comment, the "fast" and "slow" are not from the different timeframes, but just the periods. Looking into it.

**Comment by mementum** [comment]
As a 1st hint and temporary solution:

```python
cerebro = bt.Cerebro(runonce=False)
```

This will let you have access to `[0]` in the large-timeframe _lines object_ `reversal`

**Comment by mementum** [comment]
A fix has been commited and pushed to the development branch. You should now be able to `run` in the default `runonce=True` mode (faster than otherwise)

**Comment by kunalpawaskar** [comment]
That worked, thanks!
