### ISSUE TITLE
Issue with cerebro.opstrategy() in QuickStart tutorial

### ISSUE THREAD

**Issue by joepro123** [mementum/backtrader#93]
Hi, I'm managed to run most of the QuickStart tutorial, however facing an issue with the last section on optimising inputs. I get the following error message. Hope for some help, thanks!

> Exception in thread Thread-9:
> Traceback (most recent call last):
>   File "E:\Python\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "E:\Python\Anaconda3\lib\threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "E:\Python\Anaconda3\lib\multiprocessing\pool.py", line 429, in _handle_results
>     task = get()
>   File "E:\Python\Anaconda3\lib\multiprocessing\connection.py", line 251, in recv
>     return ForkingPickler.loads(buf.getbuffer())
> AttributeError: Can't get attribute 'TestStrategy' on <module '__main__' (<_frozen_importlib_external.SourceFileLoader object at 0x000002154FAEF2E8>)>

**Comment by mementum** [comment]
Below is the output of a direct run I did of the code in the *QuickStart* for the optimization script `quickstart11.py`.

Executed with Python 2.7, 3.4 and 3.5 and the result was always the same.

I don't know what this might be: `<_frozen_importlib_external`, but the `frozen` is something I would attribute to a packaged application and that's where the failure happens.

```
$ ./quickstart11.py
2000-12-29, (MA Period 10) Ending Value 880.30
2000-12-29, (MA Period 13) Ending Value 893.90
2000-12-29, (MA Period 12) Ending Value 830.30
2000-12-29, (MA Period 14) Ending Value 896.90
2000-12-29, (MA Period 11) Ending Value 880.00
2000-12-29, (MA Period 16) Ending Value 959.40
2000-12-29, (MA Period 15) Ending Value 973.90
2000-12-29, (MA Period 17) Ending Value 949.80
2000-12-29, (MA Period 18) Ending Value 1011.90
2000-12-29, (MA Period 20) Ending Value 1078.00
2000-12-29, (MA Period 21) Ending Value 1058.80
2000-12-29, (MA Period 22) Ending Value 1061.50
2000-12-29, (MA Period 19) Ending Value 1041.90
2000-12-29, (MA Period 23) Ending Value 1023.00
2000-12-29, (MA Period 24) Ending Value 1020.10
2000-12-29, (MA Period 25) Ending Value 1013.30
2000-12-29, (MA Period 26) Ending Value 998.30
2000-12-29, (MA Period 27) Ending Value 982.20
2000-12-29, (MA Period 28) Ending Value 975.70
2000-12-29, (MA Period 29) Ending Value 983.30
2000-12-29, (MA Period 30) Ending Value 979.80
```
