### ISSUE TITLE
Interactive Brokers Module

### ISSUE THREAD

**Issue by plavine** [mementum/backtrader#99]
Is there and issue with the pip installation?

Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import backtrader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/backtrader/__init__.py", line 54, in <module>
    from . import feeds
  File "/usr/local/lib/python2.7/dist-packages/backtrader/feeds/__init__.py", line 32, in <module>
    from .ibdata import *
  File "/usr/local/lib/python2.7/dist-packages/backtrader/feeds/ibdata.py", line 30, in <module>
    from backtrader.stores import ibstore
  File "/usr/local/lib/python2.7/dist-packages/backtrader/stores/__init__.py", line 27, in <module>
    from .ibstore import IBStore
  File "/usr/local/lib/python2.7/dist-packages/backtrader/stores/ibstore.py", line 33, in <module>
    from ib.ext.Contract import Contract
ImportError: No module named ib.ext.Contract

**Comment by mementum** [comment]
Indeed there is something wrong. A real oversight. Testing the latest stages of the 1st live data feed and broker integration and conditional import of the modules which give support to it is obviously not in place.

To be fixed asap.

**Comment by mementum** [comment]
Released the correction as 1.3.3.92
